# Importing Libraries

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data

In [2]:
df = pd.read_csv(r"..\data\Kaggle_dataset\AmazonProductReviewsDataset.csv", encoding='latin-1')
df.to_excel(r"..\data\product_rating_clean.xlsx", index=False)
df = pd.read_excel(r"..\data\product_rating_clean.xlsx")

# View Data

In [3]:
df.head()             # First 5 rows
df.tail()             # Last 5 rows
df.sample(10)          # Random 10 rows

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
1052,AVpfpK8KLJeJML43BCuD,B01BH83OOM,Amazon,"Amazon Devices,Home,Smart Home & Connected Liv...",Black,2017-01-04T03:51:17Z,2017-08-13T08:31:07Z,4.8 in x 6.6 in x 3.2 in,8.416670e+11,amazontapalexaenabledportablebluetoothspeaker/...,...,5.0,http://reviews.bestbuy.com/3545/5097300/review...,Alexa works great. It was easy to set-up and t...,Two thumbs up.,NaN,NaN,danmiller,NaN,8.416670e+11,1.75 lbs
1086,AVpfpK8KLJeJML43BCuD,B01BH83OOM,Amazon,"Amazon Devices,Home,Smart Home & Connected Liv...",Black,2017-01-04T03:51:17Z,2017-08-13T08:31:07Z,4.8 in x 6.6 in x 3.2 in,8.416670e+11,amazontapalexaenabledportablebluetoothspeaker/...,...,4.0,http://reviews.bestbuy.com/3545/5097300/review...,"Amazon Tap pretty much works as advertised, an...","works well, needs alittle more depth in searching",NaN,NaN,Slamajama,NaN,8.416670e+11,1.75 lbs
127,AVpfpzCi1cnluZ0-oxEr,B00DOPNLJ0,Amazon,Amazon Devices,NaN,2015-06-02T08:44:19Z,2017-08-07T15:41:59Z,NaN,NaN,kindlefirehdx89/b00dopnlj0,...,NaN,http://www.amazon.com/Kindle-Fire-HDX-Display-...,If you like the Kindle Fire HD then you will l...,"Rocks! Power Adapter included, Prime download ...",NaN,NaN,"Things I Love Like,",NaN,NaN,NaN
733,AVpf0MlqLJeJML43EQEi,"B008GGCAVM,B00DOPNMVM",Amazon,"Amazon Devices,Kindle Store",NaN,2015-06-02T08:45:09Z,2017-07-18T23:52:58Z,NaN,NaN,"kindlefirehd7/b008ggcavm,kindlefirehd7/b00dopnmvm",...,NaN,http://www.amazon.com/Kindle-Fire-Display-Wi-F...,An Amazon.com official commented on this revie...,"Decent, inexpensive, entry-level tablet 5,933 ...",NaN,NaN,NF,NaN,NaN,NaN
1574,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,5.0,https://www.amazon.com/Replacement-Remote-Amaz...,It's small and I don't miss voice interface. T...,This is a great inexpensive way to add 2nd rem...,NaN,NaN,Fixer-upper,NaN,NaN,2.4 ounces
132,AVpfpzCi1cnluZ0-oxEr,B00DOPNLJ0,Amazon,Amazon Devices,NaN,2015-06-02T08:44:19Z,2017-08-07T15:41:59Z,NaN,NaN,kindlefirehdx89/b00dopnlj0,...,3.0,http://www.amazon.com/Kindle-Fire-HDX-Display-...,Updated 12/8/2014One year in...This review is ...,KF HDX 8.9 is ok do homework on Prime download...,NaN,NaN,B. Tarbuck,NaN,NaN,NaN
1133,AVpfpK8KLJeJML43BCuD,B01BH83OOM,Amazon,"Amazon Devices,Home,Smart Home & Connected Liv...",Black,2017-01-04T03:51:17Z,2017-08-13T08:31:07Z,4.8 in x 6.6 in x 3.2 in,8.416670e+11,amazontapalexaenabledportablebluetoothspeaker/...,...,5.0,http://reviews.bestbuy.com/3545/5097300/review...,"It's not the echo but for what I paid, it's we...",Love my tap,NaN,NaN,Ces0983,NaN,8.416670e+11,1.75 lbs
1446,AVpge-anilAPnD_xtDVf,B00HX0SRXW,Amazon,"Amazon Devices,Corded Headsets,Electronics Fea...",Black,2015-07-13T14:50:00Z,2017-08-13T08:29:03Z,NaN,8.487190e+11,"amazonpremiumheadphones/b00hx0srxw,08487190395...",...,NaN,http://www.amazon.com/Amazon-KA416Y-Premium-He...,"I bought these for a couple of reasons.First, ...",I hate having to shove headphones into my brai...,NaN,NaN,Andrew,NaN,8.487190e+11,NaN
362,AVpfLiCSilAPnD_xWpk_,B00CX5P8FC,Amazon,"Categories,Amazon Devices,Electronics Features...",NaN,2015-05-22T18:12:20Z,2017-08-08T22:03:26Z,NaN,8.487190e+11,"848719022827,0848719022827,amazonfiretv/b00cx5...",...,NaN,http://www.amazon.com/Fire-TV-streaming-media-...,"Ok first off, if you are looking to get one of...",Pretty Good So Far,NaN,NaN,EvenGodHatesApple,NaN,8.487190e+11,NaN
1348,AVpfpK8KLJeJML43BCuD,B01BH83OOM,Amazon,"Amazon Devices,Home,Smart Home & Connected Liv...",Black,2017-01-04T03:51:17Z,2017-08-13T08:31:07Z,4.8 in x 6.6 in x 3.2 in,8.416670e+11,amazontapalexaenabledportablebluetoothspeaker/...,...,5.0,http://reviews.bestbuy.com/3545/5097300/review...,This is not like the Amazon Echo however this ...,Great speaker,NaN,NaN,WMMANAGEMENT,NaN,8.416670e+11,1.75 lbs

# Inspect Structure

In [4]:
df.shape              # Rows and columns
df.columns            # Column names
df.info()             # Data types and nulls
df.describe()         # Summary stats

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1597 non-null   object
 1   asins                 1597 non-null   object
 2   brand                 1597 non-null   object
 3   categories            1597 non-null   object
 4   colors                774 non-null    object
 5   dateAdded             1597 non-null   object
 6   dateUpdated           1597 non-null   object
 7   dimension             565 non-null    object
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   object
 10  manufacturer          965 non-null    object
 11  manufacturerNumber    902 non-null    object
 12  name                  1597 non-null   object
 13  prices                1597 non-null   object
 14  reviews.date          1217 non-null   object
 15  reviews.doRecommend   539 non-null    float64
 16  reviews.numHelpful    900 non-null    float64
 17  reviews.rating        1177 non-null   float64
 18  reviews.sourceURLs    1597 non-null   object
 19  reviews.text          1597 non-null   object
 20  reviews.title         1580 non-null   object
 21  reviews.userCity      0 non-null      float64
 22  reviews.userProvince  0 non-null      float64
 23  reviews.username      1580 non-null   object
 24  sizes                 0 non-null      float64
 25  upc                   898 non-null    float64
 26  weight                686 non-null    object
dtypes: float64(8), object(19)
memory usage: 337.0+ KB

,ean,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.userCity,reviews.userProvince,sizes,upc
count,8.980000e+02,539.00000,900.000000,1177.000000,0.0,0.0,0.0,8.980000e+02
mean,8.443135e+11,0.93321,83.584444,4.359388,NaN,NaN,NaN,8.443135e+11
std,3.416444e+09,0.24989,197.150238,1.021445,NaN,NaN,NaN,3.416444e+09
min,8.416670e+11,0.00000,0.000000,1.000000,NaN,NaN,NaN,8.416670e+11
25%,8.416670e+11,1.00000,0.000000,4.000000,NaN,NaN,NaN,8.416670e+11
50%,8.416670e+11,1.00000,0.000000,5.000000,NaN,NaN,NaN,8.416670e+11
75%,8.487190e+11,1.00000,34.000000,5.000000,NaN,NaN,NaN,8.487190e+11
max,8.487190e+11,1.00000,997.000000,5.000000,NaN,NaN,NaN,8.487190e+11

# Handling Missing Data

In [5]:
df.isnull().sum()                                  # Count nulls
df = df.dropna(subset=['reviews.rating', 'name'])  # Drop rows with essential nulls
df['colors'] = df['colors'].fillna('Unknown')      # Fill missing colors
df['reviews.numHelpful'] = df['reviews.numHelpful'].fillna(0)  # Fill missing numeric values
df['weight'] = df['weight'].fillna('Unknown')      # Fill missing weight

# Removing Duplicates

In [6]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

# Selecting Columns

In [7]:
df['name']                        # Single column
df[['name', 'reviews.rating']]    # Multiple columns

                                                   name  reviews.rating
0                                     Kindle Paperwhite             5.0
1                                     Kindle Paperwhite             5.0
2                                     Kindle Paperwhite             4.0
3                                     Kindle Paperwhite             5.0
4                                     Kindle Paperwhite             5.0
...                                                 ...             ...
1592  Alexa Voice Remote for Amazon Fire TV and Fire...             3.0
1593  Alexa Voice Remote for Amazon Fire TV and Fire...             1.0
1594  Alexa Voice Remote for Amazon Fire TV and Fire...             1.0
1595  Alexa Voice Remote for Amazon Fire TV and Fire...             3.0
1596  Alexa Voice Remote for Amazon Fire TV and Fire...             1.0

[1177 rows x 2 columns]

# Filtering Rows

In [9]:
df = df[df['reviews.text'].notna()]       
df = df[df['reviews.rating'] > 0]   
# Drop unnecessary columns
df = df.drop(columns=['reviews.sourceURLs', 'manufacturerNumber', 'upc'])

df.head()      # Display filtered rows

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,139.0,5.0,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,126.0,5.0,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,69.0,4.0,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,2.0,5.0,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,17.0,5.0,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,205 grams

# Sorting Data

In [10]:
df.sort_values(by='reviews.rating', ascending=True)                     # Sort by rating descending
df.sort_values(by=['brand', 'reviews.rating'], ascending=[True, False])  # Sort by brand ascending, rating descending

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,139.0,5.0,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,126.0,5.0,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,2.0,5.0,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,17.0,5.0,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,205 grams
14,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",Unknown,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,NaN,0.0,5.0,This is a review of the Kindle Paperwhite laun...,Superb reading device - but which one's best f...,NaN,NaN,John Kat's the brains,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,AVph_N4z1cnluZ0-IkrF,B00K5W9WZW,Moshi,"Cell Phones & Accessories,Accessories,Screen P...",Clear,2016-05-24T02:12:23Z,2017-08-11T12:51:38Z,NaN,NaN,moshiantiglarenobubblescreenprotectorforfireph...,...,NaN,0.0,2.0,"This one really does not have bubble problems,...",Secondly it is really soft actually thus it wi...,NaN,NaN,Yang Hua,NaN,0.8 ounces
1394,AVph_N4z1cnluZ0-IkrF,B00K5W9WZW,Moshi,"Cell Phones & Accessories,Accessories,Screen P...",Clear,2016-05-24T02:12:23Z,2017-08-11T12:51:38Z,NaN,NaN,moshiantiglarenobubblescreenprotectorforfireph...,...,NaN,0.0,1.0,"UPDATE: July 6, 2015I'm reducing my rating to ...",Updated Downgrade,NaN,NaN,Richard The Buying Hearted,NaN,0.8 ounces
1401,AVph_N4z1cnluZ0-IkrF,B00K5W9WZW,Moshi,"Cell Phones & Accessories,Accessories,Screen P...",Clear,2016-05-24T02:12:23Z,2017-08-11T12:51:38Z,NaN,NaN,moshiantiglarenobubblescreenprotectorforfireph...,...,NaN,0.0,1.0,This was a complete waste of 24. I read review...,a piece of plastic!,NaN,NaN,Amazon Customer,NaN,0.8 ounces
1402,AVph_N4z1cnluZ0-IkrF,B00K5W9WZW,Moshi,"Cell Phones & Accessories,Accessories,Screen P...",Clear,2016-05-24T02:12:23Z,2017-08-11T12:51:38Z,NaN,NaN,moshiantiglarenobubblescreenprotectorforfireph...,...,NaN,25.0,1.0,For the love of god do not buy this!!! Thought...,For the love of god do not buy this,NaN,NaN,Trever Murawski,NaN,0.8 ounces
1403,AVph_N4z1cnluZ0-IkrF,B00K5W9WZW,Moshi,"Cell Phones & Accessories,Accessories,Screen P...",Clear,2016-05-24T02:12:23Z,2017-08-11T12:51:38Z,NaN,NaN,moshiantiglarenobubblescreenprotectorforfireph...,...,NaN,0.0,1.0,"Ordered on April 16th, installed on my phone o...",Worked great... For less than two months. One ...,NaN,NaN,Javier Gutierrez,NaN,0.8 ounces

# Grouping and Aggregation

In [11]:
# Simplify categories by taking only the first category
df['main_category'] = df['categories'].str.split(',').str[0]

# Median rating by brand and main category
median_ratings = df.groupby(['brand', 'main_category'])['reviews.rating'].median()
print(median_ratings)

# Optional: Average helpful votes by brand and main category
helpful_votes = df.groupby(['brand', 'main_category'])['reviews.numHelpful'].sum()
print(helpful_votes)

brand   main_category
Amazon  Amazon Devices                  5.0
        Amazon Devices & Accessories    3.0
        Categories                      5.0
        Electronics                     5.0
        Kindle Store                    4.0
Moshi   Cell Phones & Accessories       4.5
Name: reviews.rating, dtype: float64
brand   main_category
Amazon  Amazon Devices                  61811.0
        Amazon Devices & Accessories     4104.0
        Categories                          0.0
        Electronics                      9252.0
        Kindle Store                        0.0
Moshi   Cell Phones & Accessories          59.0
Name: reviews.numHelpful, dtype: float64

# Aggregating Multiple Columns

In [12]:
df.groupby('brand').agg({
    'reviews.rating': ['mean', 'median', 'max'],        # Aggregate ratings
    'reviews.numHelpful': ['sum', 'mean', 'max']       # Aggregate helpful votes
})

       reviews.rating             reviews.numHelpful
                 mean median  max                sum       mean    max
brand
Amazon       4.369957    5.0  5.0            75167.0  64.521030  997.0
Moshi        3.333333    4.5  5.0               59.0   4.916667   25.0

# Merging DataFrames

In [13]:

# Load datasets
df1 = pd.read_csv(r"..\data\Kaggle_dataset\amazon_review.csv", encoding='latin-1')
df2 = pd.read_csv(r"..\data\Kaggle_dataset\AmazonProductReviewsDataset.csv", encoding='latin-1')

# Standardize column names (lowercase, strip spaces)
df1.columns = df1.columns.str.strip().str.lower()
df2.columns = df2.columns.str.strip().str.lower()

# Align column names: rename 'overall' -> 'reviews.rating' if exists
if 'overall' in df1.columns:
    df1.rename(columns={'overall': 'reviews.rating'}, inplace=True)
if 'overall' in df2.columns:
    df2.rename(columns={'overall': 'reviews.rating'}, inplace=True)

# Concatenate datasets row-wise
df = pd.concat([df1, df2], ignore_index=True)

# Remove duplicate column names (keep first occurrence)
if df.columns.duplicated().any():
    df = df.loc[:, ~df.columns.duplicated()]

# Drop duplicate rows
df.drop_duplicates(inplace=True)

# Final check
print("Final shape:", df.shape)
print(df.columns.tolist())   # Show cleaned column list
print(df.head())

Final shape: (6512, 39)
['reviewerid', 'asin', 'reviewername', 'helpful', 'review', 'rate', 'summary', 'unixreviewtime', 'reviewtime', 'day_diff', 'helpful_yes', 'total_vote', 'id', 'asins', 'brand', 'categories', 'colors', 'dateadded', 'dateupdated', 'dimension', 'ean', 'keys', 'manufacturer', 'manufacturernumber', 'name', 'prices', 'reviews.date', 'reviews.dorecommend', 'reviews.numhelpful', 'reviews.rating', 'reviews.sourceurls', 'reviews.text', 'reviews.title', 'reviews.usercity', 'reviews.userprovince', 'reviews.username', 'sizes', 'upc', 'weight']
       reviewerid        asin  reviewername helpful  \
0  A3SBTW3WS4IQSN  B007WTAJTO           NaN  [0, 0]
1  A18K1ODH1I2MVB  B007WTAJTO          0mie  [0, 0]
2  A2FII3I2MBMUIA  B007WTAJTO           1K3  [0, 0]
3   A3H99DFEG68SR  B007WTAJTO           1m2  [0, 0]
4  A375ZM4U047O79  B007WTAJTO  2&amp;1/2Men  [0, 0]

                                              review  rate  \
0                                         No issues.   4.0
1  Purchased this for my device, it worked as adv...   5.0
2  it works as expected. I should have sprung for...   4.0
3  This think has worked out great.Had a diff. br...   5.0
4  Bought it with Retail Packaging, arrived legit...   5.0

                                  summary  unixreviewtime  reviewtime  \
0                              Four Stars    1.406074e+09  23-07-2014
1                           MOAR SPACE!!!    1.382659e+09  25-10-2013
2               nothing to really say....    1.356221e+09  23-12-2012
3  Great buy at this price!!!  *** UPDATE    1.384992e+09  21-11-2013
4                        best deal around    1.373674e+09  13-07-2013

   day_diff  ...  reviews.rating  reviews.sourceurls reviews.text  \
0     138.0  ...             NaN                 NaN          NaN
1     409.0  ...             NaN                 NaN          NaN
2     715.0  ...             NaN                 NaN          NaN
3     382.0  ...             NaN                 NaN          NaN
4     513.0  ...             NaN                 NaN          NaN

  reviews.title reviews.usercity reviews.userprovince reviews.username sizes  \
0           NaN              NaN                  NaN              NaN   NaN
1           NaN              NaN                  NaN              NaN   NaN
2           NaN              NaN                  NaN              NaN   NaN
3           NaN              NaN                  NaN              NaN   NaN
4           NaN              NaN                  NaN              NaN   NaN

  upc weight
0 NaN    NaN
1 NaN    NaN
2 NaN    NaN
3 NaN    NaN
4 NaN    NaN

[5 rows x 39 columns]

# Concatenating DataFrame

In [14]:

df_combined = pd.concat([df, df2], axis=0, ignore_index=True)

print("Shape after concatenation:", df_combined.shape)
print(df_combined.head())

Shape after concatenation: (8109, 39)
       reviewerid        asin  reviewername helpful  \
0  A3SBTW3WS4IQSN  B007WTAJTO           NaN  [0, 0]
1  A18K1ODH1I2MVB  B007WTAJTO          0mie  [0, 0]
2  A2FII3I2MBMUIA  B007WTAJTO           1K3  [0, 0]
3   A3H99DFEG68SR  B007WTAJTO           1m2  [0, 0]
4  A375ZM4U047O79  B007WTAJTO  2&amp;1/2Men  [0, 0]

                                              review  rate  \
0                                         No issues.   4.0
1  Purchased this for my device, it worked as adv...   5.0
2  it works as expected. I should have sprung for...   4.0
3  This think has worked out great.Had a diff. br...   5.0
4  Bought it with Retail Packaging, arrived legit...   5.0

                                  summary  unixreviewtime  reviewtime  \
0                              Four Stars    1.406074e+09  23-07-2014
1                           MOAR SPACE!!!    1.382659e+09  25-10-2013
2               nothing to really say....    1.356221e+09  23-12-2012
3  Great buy at this price!!!  *** UPDATE    1.384992e+09  21-11-2013
4                        best deal around    1.373674e+09  13-07-2013

   day_diff  ...  reviews.rating  reviews.sourceurls reviews.text  \
0     138.0  ...             NaN                 NaN          NaN
1     409.0  ...             NaN                 NaN          NaN
2     715.0  ...             NaN                 NaN          NaN
3     382.0  ...             NaN                 NaN          NaN
4     513.0  ...             NaN                 NaN          NaN

  reviews.title reviews.usercity reviews.userprovince reviews.username sizes  \
0           NaN              NaN                  NaN              NaN   NaN
1           NaN              NaN                  NaN              NaN   NaN
2           NaN              NaN                  NaN              NaN   NaN
3           NaN              NaN                  NaN              NaN   NaN
4           NaN              NaN                  NaN              NaN   NaN

  upc weight
0 NaN    NaN
1 NaN    NaN
2 NaN    NaN
3 NaN    NaN
4 NaN    NaN

[5 rows x 39 columns]

# Pivot Table

In [15]:
print(df.columns)

Index(['reviewerid', 'asin', 'reviewername', 'helpful', 'review', 'rate',
       'summary', 'unixreviewtime', 'reviewtime', 'day_diff', 'helpful_yes',
       'total_vote', 'id', 'asins', 'brand', 'categories', 'colors',
       'dateadded', 'dateupdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturernumber', 'name', 'prices', 'reviews.date',
       'reviews.dorecommend', 'reviews.numhelpful', 'reviews.rating',
       'reviews.sourceurls', 'reviews.text', 'reviews.title',
       'reviews.usercity', 'reviews.userprovince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

# Renaming Columns

In [16]:

df.rename(columns={
    'reviews.rating_x': 'reviews.rating',
    'reviews.numhelpful_x': 'reviews.numhelpful',
    'reviews.text_x': 'reviews.text'
}, inplace=True)

# Check renamed columns
print(df.columns.tolist())

['reviewerid', 'asin', 'reviewername', 'helpful', 'review', 'rate', 'summary', 'unixreviewtime', 'reviewtime', 'day_diff', 'helpful_yes', 'total_vote', 'id', 'asins', 'brand', 'categories', 'colors', 'dateadded', 'dateupdated', 'dimension', 'ean', 'keys', 'manufacturer', 'manufacturernumber', 'name', 'prices', 'reviews.date', 'reviews.dorecommend', 'reviews.numhelpful', 'reviews.rating', 'reviews.sourceurls', 'reviews.text', 'reviews.title', 'reviews.usercity', 'reviews.userprovince', 'reviews.username', 'sizes', 'upc', 'weight']

# Resetting and Setting Index

In [17]:
# Reset index
df.reset_index(drop=True, inplace=True)

# Set an existing column as index
df.set_index('reviewerid', inplace=True)


print(df.head())

                      asin  reviewername helpful  \
reviewerid
A3SBTW3WS4IQSN  B007WTAJTO           NaN  [0, 0]
A18K1ODH1I2MVB  B007WTAJTO          0mie  [0, 0]
A2FII3I2MBMUIA  B007WTAJTO           1K3  [0, 0]
A3H99DFEG68SR   B007WTAJTO           1m2  [0, 0]
A375ZM4U047O79  B007WTAJTO  2&amp;1/2Men  [0, 0]

                                                           review  rate  \
reviewerid
A3SBTW3WS4IQSN                                         No issues.   4.0
A18K1ODH1I2MVB  Purchased this for my device, it worked as adv...   5.0
A2FII3I2MBMUIA  it works as expected. I should have sprung for...   4.0
A3H99DFEG68SR   This think has worked out great.Had a diff. br...   5.0
A375ZM4U047O79  Bought it with Retail Packaging, arrived legit...   5.0

                                               summary  unixreviewtime  \
reviewerid
A3SBTW3WS4IQSN                              Four Stars    1.406074e+09
A18K1ODH1I2MVB                           MOAR SPACE!!!    1.382659e+09
A2FII3I2MBMUIA               nothing to really say....    1.356221e+09
A3H99DFEG68SR   Great buy at this price!!!  *** UPDATE    1.384992e+09
A375ZM4U047O79                        best deal around    1.373674e+09

                reviewtime  day_diff  helpful_yes  ...  reviews.rating  \
reviewerid                                         ...
A3SBTW3WS4IQSN  23-07-2014     138.0          0.0  ...             NaN
A18K1ODH1I2MVB  25-10-2013     409.0          0.0  ...             NaN
A2FII3I2MBMUIA  23-12-2012     715.0          0.0  ...             NaN
A3H99DFEG68SR   21-11-2013     382.0          0.0  ...             NaN
A375ZM4U047O79  13-07-2013     513.0          0.0  ...             NaN

               reviews.sourceurls reviews.text reviews.title reviews.usercity  \
reviewerid
A3SBTW3WS4IQSN                NaN          NaN           NaN              NaN
A18K1ODH1I2MVB                NaN          NaN           NaN              NaN
A2FII3I2MBMUIA                NaN          NaN           NaN              NaN
A3H99DFEG68SR                 NaN          NaN           NaN              NaN
A375ZM4U047O79                NaN          NaN           NaN              NaN

               reviews.userprovince reviews.username sizes upc  weight
reviewerid
A3SBTW3WS4IQSN                  NaN              NaN   NaN NaN     NaN
A18K1ODH1I2MVB                  NaN              NaN   NaN NaN     NaN
A2FII3I2MBMUIA                  NaN              NaN   NaN NaN     NaN
A3H99DFEG68SR                   NaN              NaN   NaN NaN     NaN
A375ZM4U047O79                  NaN              NaN   NaN NaN     NaN

[5 rows x 38 columns]

# Text Cleaning (removing unnecessary emojis, symbols etc)

In [18]:
import re

def clean_text(text):
    if pd.isna(text):
        return ""
    text = re.sub(r"http\S+", "", text)        # remove URLs
    text = re.sub(r"&[a-z]+;", "", text)       # remove HTML entities
    text = re.sub(r"[^A-Za-z0-9\s]", "", text) # remove special characters
    text = text.lower().strip()
    return text

df['reviews.text'] = df['reviews.text'].apply(clean_text)
df['summary'] = df['summary'].apply(clean_text)

# Save Cleaned Data

In [19]:
# Save cleaned DataFrame to CSV
df.to_csv(r"..\data\cleaned_amazon_reviews.csv", index=False)

# Save cleaned DataFrame to Excel
df.to_excel(r"..\data\cleaned_amazon_reviews.xlsx", index=False)

print("Files saved successfully")

Files saved successfully!